=== cpsing/tddl/tddl-common/src/main/resources/META-INF/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://github.com/tddl/tddl/schema/table" xmlns="https://github.com/tddl/tddl/schema/table" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="tables">
        <xs:annotation>
        	<xs:documentation>tables config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
            	<xs:element ref="table" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="table">
		<xs:annotation>
			<xs:documentation>table config</xs:documentation>
		</xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="columns" maxOccurs="1" />
        		<xs:element ref="primaryKey" maxOccurs="1" />
        		<xs:element ref="partitionColumns" maxOccurs="1" />
        		<xs:element ref="secondaryIndexes" maxOccurs="1" />
        	</xs:choice>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>table name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="columns">
        <xs:annotation>
        	<xs:documentation>columns config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:sequence>
        		<xs:element ref="column" minOccurs="1" maxOccurs="unbounded" />
        	</xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="column">
        <xs:complexType>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="type" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="alias" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column alias</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="nullable" type="xs:boolean" use="optional" default="true">
        		<xs:annotation>
        			<xs:documentation>column nullable</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="primaryKey" type="xs:string" />
    
    <xs:element name="secondaryIndexes">
        <xs:annotation>
        	<xs:documentation>secondary indexes config</xs:documentation>
        </xs:annotation>
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="indexMeta" maxOccurs="unbounded" />
        	</xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="indexMeta">
        <xs:complexType>
        	<xs:choice maxOccurs="unbounded">
        		<xs:element ref="keys" maxOccurs="1" />
        		<xs:element ref="values" maxOccurs="1" />
        		<xs:element ref="partitionColumns" maxOccurs="1" />
        	</xs:choice>
        	<xs:attribute name="name" type="xs:string" use="required" >
        		<xs:annotation>
        			<xs:documentation>column name</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="type" type="xs:string" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        	<xs:attribute name="strongConsistent" type="xs:boolean" use="optional" >
        		<xs:annotation>
        			<xs:documentation>column type</xs:documentation>
        		</xs:annotation>
        	</xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="keys" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes keys config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="values" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes values config</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="partitionColumns" type="xs:string">
        <xs:annotation>
        	<xs:documentation>secondary indexes partitionColumns config</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>

=== cpsing/tddl/tddl-optimizer/src/test/resources/config/test_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables xmlns="https://github.com/tddl/tddl/schema/table" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://github.com/tddl/tddl/schema/table https://raw.github.com/tddl/tddl/master/tddl-common/src/main/resources/META-INF/table.xsd">
    
	<table name="student">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="user">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="address" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	
	<table name="orders">
		<columns>
			<column name="id" type="long" />
			<column name="buyer_id" type="string" />
			<column name="seller_id" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="buyer_id_idx" type="btree">
				<keys>buyer_id</keys>
				<values>id</values>
			</indexMeta>
			<indexMeta name="seller_id_idx" type="btree">
				<keys>seller_id</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="student_shard_by_id_and_name">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="long" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="table1">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	<table name="table2">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="table3">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
			<column name="score" type="long" />
		</columns>
		<primaryKey>id</primaryKey>
	</table>
	
	<table name="table4">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>

	<table name="table5">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>

	<table name="table6">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	<table name="table7">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
	</table>

	<table name="table8">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
	</table>

	<table name="table9">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
			<column name="c1" type="long" />
			<column name="c2" type="long" />
			<column name="c3" type="long" />
			<column name="c4" type="long" />
			<column name="c5" type="long" />
			<column name="c6" type="long" />
			<column name="c7" type="long" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx2" type="btree">
				<keys>school</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx3" type="btree">
				<keys>c1</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx4" type="btree">
				<keys>c2</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx5" type="btree">
				<keys>c3</keys>
				<values>id</values>
			</indexMeta>


			<indexMeta name="second_idx3" type="btree">
				<keys>c1,c2</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx4" type="btree">
				<keys>c2,c3</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx5" type="btree">
				<keys>c3,c1</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx6" type="inverse">
				<keys>c4</keys>
				<values>id</values>
			</indexMeta>

			<indexMeta name="second_idx7" type="inverse">
				<keys>c5</keys>
				<values>id</values>
			</indexMeta>
			
			<indexMeta name="second_idx7" type="inverse">
				<keys>c6</keys>
				<values>id</values>
			</indexMeta>
			<indexMeta name="second_idx7" type="inverse">
				<keys>c7</keys>
				<values>id</values>
			</indexMeta>
			
			
			<indexMeta name="second_idx3" type="btree">
				<keys>c6,c7</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>

	<table name="table10">
		<columns>
			<column name="id" type="long" />
			<column name="c1" type="long" />
			<column name="c2" type="long" />
		</columns>
		<primaryKey>id</primaryKey>


		<secondaryIndexes>
			<indexMeta name="c1_index" type="btree">
				<keys>c1</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="table11">
		<columns>
			<column name="id" type="long" />
			<column name="c1" type="long" />
			<column name="c2" type="long" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="c1_index" type="btree">
				<keys>c1</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="ItemInfo">
		<columns>
			<column name="userID" type="long" />
			<column name="itemID" type="long" />
			<column name="itemType" type="long" />
			<column name="info" type="string" />
		</columns>
		<primaryKey>itemID</primaryKey>
		<secondaryIndexes>
			<indexMeta name="userID_idx" type="btree">
				<keys>userID</keys>
				<values>itemID</values>
			</indexMeta>

			<indexMeta name="itemType_idx" type="btree">
				<keys>itemType</keys>
				<values>itemID</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	<table name="course">
		<columns>
			<column name="cid" type="long" />
			<column name="sid" type="long" />
			<column name="course_name" type="string" />
		</columns>

		<primaryKey>cid</primaryKey>
		<secondaryIndexes>
			<indexMeta name="course_index" type="btree">
				<keys>sid</keys>
				<values>cid</values>
			</indexMeta>
		</secondaryIndexes>
	</table>


	<table name="ItemUrl">

		<columns>
			<column name="itemUrlID" type="long" />
			<column name="userID" type="long" />
			<column name="itemID" type="long" />
			<column name="itemType" type="long" />
			<column name="url" type="string" />
		</columns>
		<primaryKey>itemUrlID</primaryKey>
		<secondaryIndexes>
			<indexMeta name="userID_idx" type="btree">
				<keys>userID</keys>
				<values>itemUrlID</values>
			</indexMeta>

			<indexMeta name="itemID_idx" type="btree">
				<keys>itemID</keys>
				<values>itemUrlID</values>
			</indexMeta>
		</secondaryIndexes>
	</table>

	
	
	<table name="t1">
		<columns>
			<column name="id" type="long" />
			<column name="name" type="string" />
			<column name="school" type="string" />
		</columns>
		<primaryKey>id</primaryKey>
		<secondaryIndexes>
			<indexMeta name="second_idx" type="btree">
				<keys>name</keys>
				<values>id</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="t2">
		<columns>
			<column name="cid" type="long" />
			<column name="sid" type="long" />
			<column name="course_name" type="string" />
		</columns>

		<primaryKey>cid</primaryKey>
		<secondaryIndexes>
			<indexMeta name="t2_index" type="btree">
				<keys>sid</keys>
				<values>cid</values>
			</indexMeta>
		</secondaryIndexes>
	</table>
	
	<table name="normaltbl_oneGroup_mutilAtom">
		<columns>
			<column name="pk" type="long" />
			<column name="id" type="int" />
			<column name="gmt_create" type="date" />
			<column name="name" type="string" />
			<column name="floatCol" type="float" />
		</columns>
		<primaryKey>pk</primaryKey>
	</table>
	
	<table name="normaltbl_mutilGroup">
		<columns>
			<column name="pk" type="long" />
			<column name="id" type="int" />
			<column name="gmt_create" type="date" />
			<column name="name" type="string" />
			<column name="floatCol" type="float" />
		</columns>
		<primaryKey>pk</primaryKey>
	</table>
</tables>
